version: '1'

services:
  zippy:
    image: zippy
    tty: true
    build:
      context: .
      dockerfile: Dockerfile
    ports:
        - 8080:8080
    depends_on:
        - mongo
        - openroute
        - redis